# Tensorflow intro

* [Официальная документация](https://www.tensorflow.org)
* [Get started](https://www.tensorflow.org/get_started/get_started)
* [Models](https://github.com/tensorflow/models/)

Из-за быстроты развития лучше всего смотреть на официальную документацию.

## Установка

Есть два типа установки: для CPU и GPU. Для CPU устанавливается стандартно через `pip`

In [ ]:
!pip install tensorflow

Для GPU немного сложнее 
* проверить совместимость с видеокартой. Параметр CUDA Compute Capability должен быть больше 3.0
* Установить CUDA Toolkit восьмой версии
* Установить cuDNN версии 5.1
* Установить из pip пакет tensorflow-gpu

Можно установить через Docker. Можно и из исходников (говорят, что так рабоатет быстрее, потому что он не тянет кучу плюшек к себе).

## Базовые элементы

Самый простой код, с помощью которого легко убедиться, что все работает.

In [2]:
import tensorflow as tf # подключаем TF
hello = tf.constant('Hello, TensorFlow!') # создаем объект из TF
sess = tf.InteractiveSession() # создаем сессию
print(sess.run(hello)) #сессия "выполняет" объект

b'Hello, TensorFlow!'


## Граф

Вся работа с TF строится вокруг построения графа вычислений. Есть гарф - есть программа. По сути - это описание того, как будут проводиться вычисления. Основа TF - создать структуру, которая задаст порядок вычислений. Соответственно программа это: 
* составление графа вычислений 
* выполнение вычислений в структурах. 

Составляющие графа:
* Плейсхолдеры
* Переменные
* Операции
Из этого собираем граф, в котором будут вычисляться тензоры. **Тензоры** это многомерные массивы, по своей сути это топливо графа.Тензором может быть как отдельное число, вектор, так и целый батч.Вместо одного объекта можно передать массив объектов - на выходе получить массив ответов. По сути это обработка массива в numpy.

## Сессия

Выполнение графа происходит в сессии (*tf.Session()*). Такой объект скрывает в себе контекст выполнения графа (ресурсы, классы, адресные пространства). Два типа сессии:
* Обычные (**tf.Session()**)
* Интерактивные (**tf.InteractiveSession()**)
Интерактивная для консоли. Основной эффект — объект сессии не нужно передавать в функции вычисления как параметр.

Tensorboard генерирует графы за вас на примере:

<img src="pic/1.png" />

## Тензоры, операции, переменные

Тензор с нулями:

In [3]:
zeros_tensor = tf.zeros([3, 3])

Для того, чтобы посмотреть тензор, необходимо выполнить его. Пока без графа:

In [5]:
print(zeros_tensor.eval())
print(zeros_tensor)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Tensor("zeros:0", shape=(3, 3), dtype=float32)


Различия: в первой строке вычисление, во второй представление объекта. Что дает описание:
* Имя тензора
* Форма тензора (размерность массива numpy)
* Типизация тензора

Есть множество операций:

In [9]:
a = tf.truncated_normal([2, 2]) #усеченое нормальное распределение
b = tf.fill([2, 2], 0.5) #массив из 0.5 
print(sess.run(a + b)) 
print(sess.run(tf.matmul(a, b)))

[[ 0.45460051  0.46388394]
 [-0.28661668  1.51374352]]
[[-1.01343989 -1.01343989]
 [-0.17550369 -0.17550369]]


** sess.run()** метод исполнения операций в графе. 

Создадим переменную на основе тензора

In [10]:
v = tf.Variable(zeros_tensor)

Почему нельзя просто задать? Так как переменная будет в качестве узла графа. Есть еще плейсхолдеры - параметризуют граф и отмечают места для постановки нужных значений (внешних) по сути - обещание поставить значение потом.

In [11]:
x = tf.placeholder(tf.float32, shape = (4, 4)) 

In [32]:
a = tf.placeholder("float")
b = tf.placeholder("float")
y = tf.multiply(a, b)
print(sess.run(y, feed_dict={a:100, b:500}))

50000.0


## Basic eval

In [33]:
x = tf.placeholder(tf.float32)
f = 1 + 2 * x + tf.pow(x, 2)
sess.run(f, feed_dict={x:10})

121.0

<img src="pic/2.png" />

In [16]:
import numpy as np
x = tf.placeholder(dtype=tf.float32)
sigma = 1 / (1 + tf.exp(-x))
sigma.eval(feed_dict={x: np.linspace(-5, 5) })

array([ 0.00669285,  0.00819568,  0.01003255,  0.01227603,  0.01501357,
        0.01835024,  0.02241159,  0.02734679,  0.03333168,  0.04057176,
        0.04930425,  0.05979915,  0.07235796,  0.0873094 ,  0.10500059,
        0.12578245,  0.14998817,  0.17790413,  0.20973383,  0.24555731,
        0.28529069,  0.32865256,  0.3751457 ,  0.42406148,  0.47451192,
        0.52548808,  0.57593852,  0.62485433,  0.67134744,  0.71470934,
        0.75444269,  0.79026616,  0.82209587,  0.85001183,  0.87421757,
        0.89499938,  0.91269064,  0.92764211,  0.94020081,  0.95069569,
        0.95942819,  0.96666825,  0.97265327,  0.97758842,  0.98164982,
        0.98498636,  0.98772395,  0.98996747,  0.99180436,  0.99330717], dtype=float32)

<img src="pic/3.png" />

В фрагменте с запуском вычисления функции есть один момент, который отличает этот пример от предыдущих. Дело в том, что в плейсхолдер вместо одного скалярного значения мы передаем целый массив. TF обрабатывает все значения массива вместе, в рамках одного тензора (помним, что массив == тензор). Точно таким же образом мы можем передавать в граф объекты целыми батчами и поставлять нейронной сети картинки целиком.

## Сохранение и загрузка графов

Есть специальный объект-сериализатор, который делает две вещи:
1. Сохраняет текущий граф, состояние и значения в файл
2. Читает то же самое из файла

https://www.tensorflow.org/programmers_guide/variables

In [35]:
saver = tf.train.Saver()
saver.save(sess, '"test.ckpt"')

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: save_8/SaveV2 = SaveV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_8/Const_0, save_8/SaveV2/tensor_names, save_8/SaveV2/shape_and_slices, Variable)]]

Caused by op 'save_8/SaveV2', defined at:
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2787, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-35-2358f558c33b>", line 1, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 689, in build
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 276, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 219, in save_op
    tensors)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 780, in save_v2
    tensors=tensors, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value Variable
	 [[Node: save_8/SaveV2 = SaveV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_8/Const_0, save_8/SaveV2/tensor_names, save_8/SaveV2/shape_and_slices, Variable)]]


In [37]:
ckpt = tf.train.get_checkpoint_state(ckpt_dir)
if ckpt and ckpt.model_checkpoint_path:
    print(ckpt.model_checkpoint_path)
    saver.restore(session, ckpt.model_checkpoint_path)

NameError: name 'ckpt_dir' is not defined

## Tensorboard

Крайне полезная система в составе TF — web-dashboard, который позволяет собирать статистику из дампов и логов и наблюдать, что же всё-таки происходит во время вычислений. Крайне удобно то, что дашборд работает на веб-сервере и можно, например, запустив tensorboard на удаленной машине в облаке, наблюдать происходящее у себя в окне браузера.

Tensorboard умеет:

1. Рисовать граф вычислений.
2. Граф вычислений стоит посмотреть хотя бы для самопроверки, чтобы убедиться в том, что собралось и считается именно то, что планировалось, и при кодировании не допущено ошибок.
3. Показывать статистику по переменным.
4. Можно собирать вообще любую статистику.
5. Есть средство для анализа многомерных данных (например, эмбеддингов). Для этого в дашборде встроены PCA и t-SNE, с которыми можно попробовать рассмотреть данные в 2 и 3 измерениях.
6. Гистограммы. Можно строить гистограммы распределений выходов слоев сетей и поведения переменных.

Обратная сторона медали — чтобы статистика попадала в дашборд, её нужно сохранять в логи (в формате protobuf) с помощью специального API. API не очень сложный, сгруппирован в **tf.summary**. Для сбора статистики нужно будет отдельно зарегистрировать интересующие переменные с помощью специальных функций и потом отдельно сохранить всё в лог.

In [38]:
tf.summary.histogram("layer_output", v)

<tf.Tensor 'layer_output:0' shape=() dtype=string>

**tf.summary.scalar("accuracy", learning_rate)**

Сохранять логи

In [39]:
writer = tf.summary.FileWriter("./logs/nn_logs", sess.graph) # for 1.0
merged = tf.summary.merge_all()

Для простого: 

In [41]:
import os
merged = tf.summary.merge_all(key='summaries')
if not os.path.exists('tensorboard_logs/'):
    os.makedirs('tensorboard_logs/')
my_writer = tf.summary.FileWriter('tensorboard_logs/', sess.graph)

По умолчанию Tensorboard локально доступен по адресу 127.0.1.1:6006. **`tensorboard --logdir=path/to/log-directory`**

## Apache beam and tf tranform